# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

name: Build and Publish Dev Container
on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ !contains(github.ref_name, 'release/') }}

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-scan-push:
    # always build a dev (development) image
    name: Build and push development image
    uses: ./.github/workflows/build-and-push-container.yml
    with:
      image-tag-suffix: dev-${{ github.sha }}
    secrets: inherit
