# SPDX-License-Identifier: Apache-2.0
# © Crown Copyright 2025. This work has been developed by the National Digital Twin Programme
# and is legally attributed to the Department for Business and Trade (UK) as the governing entity.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and release docker images to AWS

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        description: "The tag(s) to apply to the docker images, if multiple use a comma separated list. Don't use staged as a tag."
        type: string
      jar_version:
        required: true
        description: "The version of the jar to use for the docker image"
        type: string
      docker_target:
        required: true
        description: "The target of the multistage docker build to use"
        type: string
      dry_run:
        required: false
        description: "Dry Run. Whether to push the images to GHCR or not"
        type: boolean

jobs:
  release:
    name: Build and release docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Validate docker target
        run: |
          if [[ "${{ inputs.docker_target }}" != "secure-agent-graph" ]]; then
            echo "Docker target is invalid. Use secure-agent-graph"
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecr-access-for-github
          aws-region: ${{ secrets.AWS_REGION }}
          role-skip-session-tagging: true
          role-duration-seconds: 3600

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7

      - name: Format repo name
        run: |
          echo REPO="${{ steps.login-ecr.outputs.registry }}/ndtp/secure-agent-graph" >> ${GITHUB_ENV}
    
      - name: Get server and client jars
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          pattern: secure-agent-graph-*.jar
          path: target
          merge-multiple: true

      - name: Build Server Image
        run: |
         docker build --no-cache --build-arg JAR_NAME="secure-agent-graph-${{ inputs.jar_version }}" \
          -t "${REPO}:staged" -f "${{ github.workspace }}/docker/Dockerfile" --target ${{ inputs.docker_target }} .

      - name: Run Trivy Scan on Server Docker Image
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          image-ref: "${REPO}:staged"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
        continue-on-error: true

      - name: Tag Server Image with tag(s) ${{ inputs.image_tag }}
        run: |
          ./.github/actions/docker-tags.sh "${REPO}" "${{ inputs.image_tag }}"
          docker rmi "${REPO}:staged"

      - name: Push Server Image
        if: ${{ !inputs.dry_run }}
        run: docker push --all-tags "${REPO}"
